### ISSUE TITLE
submission_recipient empty

### ISSUE THREAD

**Issue by Deepcuts** [filipnet/postfix-bounce-report#1]
Hello,

1st of all, thank you for developing this. Exactly what I was looking for.
Unfortunately, postfix-build-submission-recipients.sh runs without any error, the file submission_recipient is created in /etc/postfix but it is empty.
The script finishes in ~ 1 second.
![image](https://user-images.githubusercontent.com/4704834/140930262-21f7a075-a445-43ad-95d6-0d1f0b514453.png)

The correct maillog file is set in config.xml and it contains data (at noon was about 5 MB)
Using Postfix on Ubuntu Server with perl  5.18
Any hints as to how I can debug this?

Thank you

**Comment by Deepcuts** [comment]
Editing the file postfix-build-submission-recipients.sh and changing **f 6** to **f 5** seems to populate the file submission_recipient
`NEW=$(grep sasl_username= $MAILLOG | cut -d " " -f 6 | perl -pe 's/://g' | xargs -I MSGID grep MSGID $MAILLOG | grep to=\< | grep -v cleanup | perl -pe 's/^.+to=\<(.+)\>,.+$/$1/g' | perl -ne 'print lc' | sort | uniq)`

Now, this might be something on my end. I might have modified how Postfix logs to file, but sincerly I cannot recall.

**Comment by filipnet** [comment]
Hi, the script is based on the standard Postfix log format. If something has been changed, the statements will no longer work. I will try to help you with an example - debugging on console.

```
# Define MAILLOG variable manually
MAILLOG=/var/log/maillog
```

The script is based on SASL authentication. Authentication based on IP subnet, Dovecot-Auth are not considers in this script.

```
# Search for sent emails with SASL-Auth
$NEW = grep sasl_username= $MAILLOG
echo $NEW
Nov  9 14:25:50 mx.domain.de postfix/smtps/smtpd[455898]: 15FDE183E7146: client=unknown[192.168.2.2], sasl_method=PLAIN, sasl_username=max.mustermann
```

```
# Search for the message ID
echo $NEW | cut -d " " -f 6 | perl -pe 's/://g'
15FDE183E7146
```

```
# Search the logfile by the message ID, filtered by "to=<"
echo $NEW | cut -d " " -f 6 | perl -pe 's/://g' | xargs -I MSGID grep MSGID $MAILLOG | grep to=\< | grep -v cleanup
Nov  9 14:25:58 mx.domain.de postfix/smtp[455906]: 15FDE183E7146: to=<test@any-domain.de>, relay=none, delay=8.3, delays=8.3/0.01/0.01/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=any-domain.de type=AAAA: Host not found)
```

```
# Output everything between the "to=<" and the following ">".
echo $NEW | cut -d " " -f 6 | perl -pe 's/://g' | xargs -I MSGID grep MSGID $MAILLOG | grep to=\< | grep -v cleanup | perl -pe 's/^.+to=\<(.+)\>,.+$/$1/g'
test@any-domain.de
```

```
# At the end convert to lowercase
| perl -ne 'print lc'
# Sort
| sort 
# Remove duplicates if several identical values exist
| uniq
```

I hope this helps you.

**Comment by filipnet** [comment]
Since the request is now two weeks old and unanswered, I assume a configuration problem with your mail server and close this issue.
